### ISSUE TITLE
Amazon.CognitoIdentity error: java.io.FileNotFoundException: https://cognito-identity.eu-west-1.amazonaws.com/

### ISSUE THREAD

**Issue by seaders** [aws/aws-sdk-unity#10]
I'm using the Amazon Mobile SDK for Unity, and have an access token from Google Play (retrieved as described in https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/cognito-auth.html#use-google), but when I run 

	credentials.IdentityProvider.Logins.Add ("accounts.google.com", accessToken);
	credentials.IdentityProvider.RefreshAsync (RefreshCallback, null);
	initializationPending = false;

I get this error, https://gist.github.com/seaders/2de51c11252018361513

And I think the main issue is at,

	Amazon.CognitoIdentity error: java.io.FileNotFoundException: https://cognito-identity.eu-west-1.amazonaws.com/
	com.sixminute.freeracing E/Unity﹕ curl -X POST  -H "X-Amz-Target: AWSCognitoIdentityService.GetId"  -H "Content-Type: application/x-amz-json-1.1"  -H "User-Agent: AWS-SDK-UNITY/1.0.0"  -H "X-HTTP-Method-Override: POST"  -H "Accept: application/json"  -d '{"AccountId":"36xxxxxxxxxxx91","IdentityPoolId":"eu-west-1:f99xxxxxxxxxxxxxxxxxx926","Logins":{"accounts.google.com":"xxxxxxxxx.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwic3ViIjxxxxxxxxxQyMjI3Njc5OX0.tBXSEOBwgfDa-xxxxxxxxx-pjW1MbtaowiEzIMAtbV95OC7uZrkABU2UeGg"}}'
	com.sixminute.freeracing I/Unity﹕ CachingCognitoAWSCredentials: No valid credentials found in LocalStorage

and

	Amazon.CognitoIdentity error: java.io.FileNotFoundException: https://cognito-identity.eu-west-1.amazonaws.com/
	com.sixminute.freeracing E/Unity﹕ curl -X POST  -H "X-Amz-Target: AWSCognitoIdentityService.GetId"  -H "Content-Type: application/x-amz-json-1.1"  -H "User-Agent: AWS-SDK-UNITY/1.0.0"  -H "X-HTTP-Method-Override: POST"  -H "Accept: application/json"  -d '{"AccountId":"36xxxxxxxxxxx91","IdentityPoolId":"eu-west-1:f99xxxxxxxxxxxxxxxxxx926","Logins":{"accounts.google.com":"xxxxxxxxx.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwic3ViIjoiMTA3OTkzMzI4MTQxNDc1ODE2MzM5IiwiYXpwIjoiNDAxODIxODQ1MDE3LWtmbjM0cWJmMWliMzNzYnNpZxxxxxxxxxOjE0MjIyNzI4OTksImV4cCI6MTQyMjI3Njc5OX0.tBXSEOBwgfDa-xxxxxxxxx-pjW1MbtaowiEzIMAtbV95OC7uZrkABU2UeGg"}}'
	com.sixminute.freeracing E/Unity﹕ Cognito error: Error occured during GetCredentialsAsync

*However*, if I go and take that same access token, and pass it through on the Native app I've got up and running... We authenticate without any problem.  Also, if we log in using a Facebook access token, again, everything works without a problem.  The only issue I have is when we try to authenticate with a google access token, using the Unity SDK.

**Comment by weijiamao** [comment]
We are looking into this issue and will give you feedback soon.

**Comment by seaders** [comment]
Great, thanks weijiamao.  Let me know if you'd like me to debug new libraries, or you'd like a copy of the Unity project I'm using to test this / my Google Play access token I use to try authenticate with.  We're very eager to get this as our full game backend.

**Comment by weijiamao** [comment]
Can you send me a copy of your project with instruction to reproduce your issue? My email: mwj@amazon.com

**Comment by seaders** [comment]
Done.

**Comment by albertvaka** [comment]
Hi and sorry for the delay in our answer.

FileNotFoundException is a generic exception that is thrown in this case because the request to Cognito returns a 400 error. You can see the actual content of the error message returned by Cognito by running the "curl" command that the SDK prints in the logs.

The most likely cause is that the Client ID that you set up in the Identity Pool doesn't match the token you get from Google, so the validation fails. You can find the Client ID which this token is good for by decoding the token using this tool: http://jwt.io/ If the "azp" field is set, this is the value that is checked, otherwise is "aud".

There are two ways for you to set up the Identity Pool, depending on your use case:

* If you only have an Android *or* an iOS app associated to this Identity Pool:

In the Google Developers Console (https://console.developers.google.com) you should have two Client IDs: one for a "Service Account" that will be embed in your app and used to request the token, and one for an "Android application", that you have to enter in the Identity Pool configuration from the Cognito Console (https://console.aws.amazon.com/cognito). Note that it can look like they are swapped but that's how you have to use them.

* If you want to have multiple apps (for example Android *and* iOS) associated to this Identity Pool:

Create an OIDC provider using the IAM console (http://docs.aws.amazon.com/IAM/latest/UserGuide/identity-providers-oidc.html#manage-oidc-provider-console) and add all your Client IDs to it (Android app, iOS app and Service Account). Then from the Identity Pool configuration (https://console.aws.amazon.com/cognito) unfold the "OpenID Connect Providers" section and select the provider you just created. Finally, the Google's Client ID you have to embed in your apps to get the auth token is the one under "Service Account".

You can find more detailed instructions about supporting multiple Google Client IDs in this forum post: https://forums.aws.amazon.com/thread.jspa?messageID=596776

PS: I've seen you had to workaround the Google Unity SDK not providing the auth token (https://github.com/playgameservices/play-games-plugin-for-unity/issues/10). We apologize for the inconvenience and wanted to ask you if you would like to pull-request your changes into our sample app, so other developers can use them.

**Comment by seaders** [comment]
Hey Albert, I don't believe that's the problem however, because if I run your Android sample and use the same access token, everything works.  I've already sent my sample app to Weijia, and I could do the same with you if you wish, along with the access token that *works* from an Android native app, but doesn't work from the Unity sample app, all things being equal.

As for the pull request, sure, I'll get that up now.  FYI, it also involves using Prime31's Unity Activity Sharing system, https://gist.github.com/prime31/0908e6100d7e228f1add, instead of overriding the main activity.

**Comment by albertvaka** [comment]
Can you run the curl command to see the error returned by Cognito?

**Comment by seaders** [comment]
The URL is actually cut off at the end of that print statement for some reason, nothing to do with Logcat settings, I've tried viewing directly and with ADT and Android Studio.  The rest of the command is there, but the end is just "htt", just like in my gist.

**Comment by albertvaka** [comment]
The endpoint is https://cognito-identity.eu-west-1.amazonaws.com/

**Comment by seaders** [comment]
Response is...

{"__type":"NotAuthorizedException","message":"Token is not from a supported provider of this identity pool."}

:/ Let me run through all my Unity prefab settings to make 100% of everything, and again make 100% that the access token works fine in the native app, but not when used in Unity.

**Comment by albertvaka** [comment]
I was able to test the sample you sent us (with my own Identity Pool and my Google app) and it worked without a problem, so that's why I'm guessing it is a configuration problem.

Maybe the token you are getting using Unity is different (contains a different Client ID) that the one you get using the Android java app? (you can use http://jwt.io/ to check that) In this case, creating an OIDC provider might help because it aggregates all the Client IDs together.

**Comment by seaders** [comment]
Ok, if I use the

````java
public CognitoCachingCredentialsProvider(
  android.content.Context context,
  java.lang.String identityPoolId,
  com.amazonaws.regions.Regions region)
{ /* compiled code */ }
````

CognitoCachingCredentialsProvider signature, all is fine, but if I use the other one, similar to what's necessary for Unity,

````java
public CognitoCachingCredentialsProvider(
  android.content.Context context,
  java.lang.String accountId,
  java.lang.String identityPoolId,
  java.lang.String unauthRoleArn,
  java.lang.String authRoleArn,
  com.amazonaws.regions.Regions region)
 { /* compiled code */ }
````

I pretty much get the same error,

         Caused by: com.amazonaws.AmazonServiceException: Not authorized to perform sts:AssumeRoleWithWebIdentity (Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied; Request ID: 7d865d58-ac0c-11e4-9f21-5702f8ea3a83)

If you'd like all the settings I'm using, I'll share all my details via email, rather than here publicly, if that's ok with you?

**Comment by seaders** [comment]
*sigh*

Forget all that I've said, after going through everything again (specifically your pointer to http://jwt.io/ and debugging *exactly* what that says about the access token), it's all working 100%ly fine.

I'll get my own Google Play login project up here tomorrow, and then get the pull request done after that.  Thanks for all the help Weijia and Albert, much appreciated!

**Comment by albertvaka** [comment]
You are welcome! :)

About making a pull request, it would be nice to reduce it to the bare minimum. Specially if we can avoid having to include Prime31's Unity Activity Sharing, to prevent license problems!

**Comment by seaders** [comment]
Unfortunately that is necessary to receive the callbacks from the GooglePlay sign-in process (I'm not sure what voodoo they're doing on the official one, because it's a black-box compiled .so file only), but that project can be under SixMinute's user, and you can just reference it similar to how you reference Facebook's SDK.

For the pull request, there'd literally only be one changed file, FBLoginController gets renamed to LoginController, and it gets one more button, for logging in to Google Play, and all the extra code can go in there.  I'm completely off the same opinion, bare bones to the absolute max.

**Comment by seaders** [comment]
Would you believe, with all the trouble from the Google Login stuff, I've only just gotten around to implementing your OIDC solution now!

It worked instantly first time, but I have unfortunately now hit another snag,
https://forums.aws.amazon.com/thread.jspa?threadID=204643

Basically because we've two Identity Pools which refer to different sets of Google client IDs.  Because OIDC is referenced to provider specific instead of project specific, I'm completely blocked by this.  If you could potentially bring an internal someone's attention to this, you'd help greatly!

FYI, on the Google Play stuff, I'm near ready to create a pull request to their project to patch the holes for access token that are currently there.

*sign* Been a long, long road!

**Comment by seaders** [comment]
@albertvaka I've just created a pull request there, on the Google Play repo, but I also have a patchfile, https://gist.github.com/seaders/9786b9372023af87b1c3#file-tokenpatch-patch that, until the .unitypackage there is updated, anyone can use to give themselves the functionality.

As for my above problem, I misunderstood / forgot how some things work and it's sorted now, but I still do think that OIDC's should be project specific instead or provider specific.

**Comment by albertvaka** [comment]
@seaders Thanks for contributing your fix to Google, and also for updating this thread so people having this problem can benefit from it.

About your comment regarding OIDC, I saw your forum post in the AWS forums [1] but as Bob Kinney already replied there, unfortunately we can't promise a fix.

[1] https://forums.aws.amazon.com/message.jspa?messageID=657612#657612
