### ISSUE TITLE
CognitoAWSCredentials RemoveLogin

### ISSUE THREAD

**Issue by Deathwing** [aws/aws-sdk-unity#102]
Hey guys,

I have a question:
A player is logging in into facebook to, so I add graph.facebook.com as a new credentials login.
For now, eveything is working and fine.
But if the players logsout, and the game removes graphc.facebook.com from the credentials, he will always get a "Access to Identity forbidden" error. 
If I try to Clear() the credentials, everything is getting even worse.
How I must handle the login remover, so the player is still able to use his old identidy (like it was before he added facebook to it).

Thanks for your help!

**Comment by behrooziAWS** [comment]
Once an identity transitions from unauthenticated to authenticated, you must provide valid credentials each time you access that identity.  There is no way to downgrade an identity from authenticated to unauthenticated.

**Comment by aaronhoogstraten** [comment]
What I do and I believe a few others have mentioned, is before you remove the Facebook credentials backup your player's data. After your player receives a new identity, restore the backed up data. I did a few tests with this when the SDK was in developer preview and it seemed to work. I haven't tested this functionality since the SDK fully released though. This topic has been discussed before so you can do a search for related issues.

**Comment by karthiksaligrama** [comment]
closing this issue. Please reopen if you have any other question
