### ISSUE TITLE
Web player not working

### ISSUE THREAD

**Issue by LancelotBleu** [aws/aws-sdk-unity#14]
Our title needs to run on both the Web player and iOs versions.    We are receiving crossdomain policy errors when we try to launch from the web version.   

This is caused because Unity require that the server validate the connection using the unity call :
"Security.PrefetchSocketPolicy(dstAddressString, port);"

Errors

"curl -X POST  -H "X-Amz-Target: AWSCognitoIdentityService.GetId"  -H "Content-Type: application/x-amz-json-1.1"  -H "X-HTTP-Method-Override: POST"  -H "Accept: application/json"  -d '{"AccountId":"382057988700","IdentityPoolId":"us-east-1:8100f62b-a81c-4ad2-8ef1-ebaa24f09344"}'  https://cognito-identity.us-east-1.amazonaws.com/"

"WebException: Rejected because no crossdomain.xml policy file was found"

Is there any possible workaround around?  

Note : To reproduce this issue, simply take the cognito sync sample and switch to "File -> Build Setting -> Switch Platform : select Web player".

**Comment by albertvaka** [comment]
Hi! Thanks for raising this problem. We definitely would like to allow our SDK to work in the Unity Web Player. As far as I know, though, there is no way to workaround this security policy from Unity itself, so it would require a fix in a per-service basis.

From the error you posted I see you are trying to get credentials from Cognito Identity. However, even if we fix this for Cognito Identity, you will find the same problem again for every other service you try to access from the SDK. Could you tell us which other services are you interested in using (eg: Cognito Sync, S3, DynamoDB...)?

I will further investigate this issue and post here if there is any update in the following days.

**Comment by LancelotBleu** [comment]
Hello Albert!   We are planning to use a combination of both Cognito and DynamoDb very soon.    Afterward (over a 6-12 month period) the probability that we use S3 is very high but not prioritary for now.

I fixed this issue for my own servers in the past.    Unless you have some backdoor with Unity, you will definitively need to call the "Security.PrefetchSocketPolicy" from the client.   A very small server will be required on the other side to answer it.   I did not find any more simple workaround for this.

After the first implementation, I will guest that it should not be very difficult on your side to extend it to other AWS services if required.

**Comment by albertvaka** [comment]
Hi!

We added support for cross-domain requests (CORS) to Amazon Cognito Identity and Sync, so you should already be able to use them from a Unity Web Player. Note that, as of now, the only services supported by the Unity SDK that allow CORS are Amazon Cognito and S3, so you won't be able to use DynamoDB yet. The DynamoDB team is aware of this issue.

Albert

**Comment by LancelotBleu** [comment]
That's a very good news, thanks.   I will try it next week.   Please let me know when there will be an update on the DynamDb side.    

Nicolas

**Comment by LancelotBleu** [comment]
Hi,

I still have some problems to make it work.  I disabled DynamoDb and only Kept Cognito.   I guess that I have some updates or code to add but I'm not sure what to do.    Maybe wait for the next SDK release?

By searching the unity forums, the only thing I could find in the forums about Unity support for CORS was a call to support it 6 months ago.   I'm not sure if it is implemented yet.

http://feedback.unity3d.com/suggestions/support-cors-for-web-player-1

[15/2/2015 18:55:53] PlayerPropertiesDb:OnRefreshDataset Unable to refresh AWD Player data set. Amazon.Runtime.AmazonServiceException: Rejected because no crossdomain.xml policy file was found ---> System.Net.WebException: Rejected because no crossdomain.xml policy file was found
  --- End of inner exception stack trace ---
UnityEngine.Debug:LogWarning(Object)
DebugExt:LogWarning(String, Object[]) (at Assets/Code/Utils/Debug.cs:31)
PlayerPropertiesDB:OnRefreshDataset(AmazonCognitoResult) (at Assets/Code/Player/PlayerPropertiesDB.cs:313)
Amazon.Unity.<FireCallbackOnCoRoutine>c__Iterator3:MoveNext() (at Assets/Code/Aws/AWSUnitySDK/CognitoSync/Amazon.Unity/AmazonMainThreadDispatcher.CognitoSync.cs:38)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Amazon.Unity.AmazonMainThreadDispatcher:Update() (at Assets/Code/Aws/AWSUnitySDK/AWSCore/Amazon.Unity/AmazonMainThreadDispatcher.cs:139)

Nicolas

**Comment by albertvaka** [comment]
Do you get to see the URL that is actually being called? If it's not in the Unity logs, you might be able to get it using the browser's developer tools (usually there is a "Network" tab for this).

That would help us a lot to identify the cause of the problem.

**Comment by LancelotBleu** [comment]
In both unity logs and wireshark logs I see a call to "https://sts.amazonaws.com/".

In Wireshark I also see a previous call to  "cognito-identity.us-east1.amazonaws.com". 

![webawscrossdomainerror](https://cloud.githubusercontent.com/assets/6461434/6267725/86f643a0-b814-11e4-9d94-f34fd6f3e368.png)

![wiresharkawscognitoweberror](https://cloud.githubusercontent.com/assets/6461434/6267727/8dda7e48-b814-11e4-8573-410ba71bd132.png)

![wiresharkawscognitoweberror2](https://cloud.githubusercontent.com/assets/6461434/6267737/aee342a0-b814-11e4-9d6c-08aa7f82958f.png)

**Comment by LancelotBleu** [comment]
I'm looking back at Unity's scripting documentation for the web player.   Does your server is at port 843?

"A Unity webplayer needs a socket served policy in order to connect to a particular host. This policy is by default hosted by the target host on port 843 but it can be hosted on other ports as well. The functional difference with a non-default port is that it must be manually fetched with Security.PrefetchSocketPolicy() API call and if it is hosted on a port higher than 1024 the policy can only give access to other ports higher than 1024."

http://docs.unity3d.com/Manual/SecuritySandbox.html

http://docs.unity3d.com/ScriptReference/Security.PrefetchSocketPolicy.html

**Comment by albertvaka** [comment]
STS may not support CORS yet, but you can use Cognito without STS in the latest SDK (1.0.1) that was released this week. To do so:
-Go to the AWS Cognito Console, edit your identity pool and make sure your app has the roles you are using associated. 
-Change your CognitoAWSCredentials constructor and remove the acccount ID and roles from there (ie: CognitoAWSCredentials(identityPoolId, region)).

**Comment by carmonj001** [comment]
Hi! We are building a game that uses Cognito Identity and DynamoDB to store the user progress using Facebook as an external identity provider and Unity 5.1.0f3.
We got everything working fine with iOS, but when building for WebPlayer we managed to get Cognito Identity working (our login is successful and we receive the correct credentials), but when trying to access DynamoDB we get the following error:

"System.Security.SecurityException: No valid crossdomain policy available to allow access
Rejected because no crossdomain.xml policy file was found"

Does DynamoDB support CORS already? If it doesn't, is it going to be supported any time soon?

PS: to get it working for WebPlayer we had to comment out some lines in your SDK to avoid compile errors, since classes like FileSystemWatcher (used in PersistenceManager.SettingsManager) are not available for WebPlayer. After doing all this, we tested again your SDK with iOS and everything still worked as usual, so we assume we didn't touch anything that may affect us.
After that, when trying to access Cognito Identity we kept getting this error: "Cannot overwrite header User-Agent", so to get it working we had to add this piece of code before line 129 in /AWSSDK/src/Core/Amazon.Runtime/Pipeline/_unity/UnityMainThreadDispatcher.cs:

    #IF UNITY_WEBPLAYER
    request.Headers.Remove("User-Agent");
    request.Headers.Remove("Content-Length");
    request.Headers.Remove("host");
    #ENDIF
    request.WwwRequest = new WWW(request.RequestUri.AbsoluteUri,
                                                              request.RequestContent, request.Headers);

Can this be causing our failure?

**Comment by karthiksaligrama** [comment]
can you tel us where you get the error? 
`"System.Security.SecurityException: No valid crossdomain policy available to allow access
Rejected because no crossdomain.xml policy file was found"` Do you get it when you try to use Security.PrefetchSocketPolicy(dstAddressString, port);

**Comment by carmonj001** [comment]
Right after we get the credentials from Cognito Identity, we try to get the user information from DynamoDB using *context.LoadAsync(userID, callback);*. After that, the execution stops at the breakpoint we set in *UnityWebResponseData.cs* line 68 so we can take a look at what there is in the wwwRequest object. The field *error* contains *"Rejected because no crossdomain.xml policy file was found"* and the field *data* contains *"System.Security.SecurityException: No valid crossdomain policy available to allow access"*.

The constructor in *UnityWebResponseData.cs* is being called from *UnityMainThreadDispatcher.InvokeRequest(UnityWebRequest request)*.

Is this information complete enough or you need something else?

**Comment by karthiksaligrama** [comment]
the web player plugin is being phased out and hence will not be supported by browsers themselves. as such unity sdk will not support webplayer.

refer http://blogs.unity3d.com/2015/10/08/unity-web-player-roadmap/
