### ISSUE TITLE
Unauthenticated login issues after an hour with Cognito

### ISSUE THREAD

**Issue by LancelotBleu** [aws/aws-sdk-unity#17]
First let me say that I really enjoy the SDK so far.    I will definitively use it.

When I play in Unity Editor PC Standalone, I noticed that If I log using FB authentication first and than at my next connection I started unauthenticated, everything works fine.

But if I wait for more than an hour I will receive errors from the SDK and it will be impossible to get a working unauthenticated session anymore.

After that, if I log back using Facebook it will just work fine for an other hour when logged unauthenticated.

Is this normal behavior?

**Comment by albertvaka** [comment]
Hi, and thanks for your comments. 

Yes, once an identity becomes authenticated (eg: with Facebook), it's not longer possible to access it without an authentication token. However, since the authentication token that you receive when you login with Facebook is valid for 1 hour, you still will be able to access it without having to send the token again for this hour. 

This is the reason why you can access the identity as "unauthenticated" (ie: without providing an authentication token) for one hour after accessing it with a Facebook login, but you will see an error afterwards.

Albert

**Comment by LancelotBleu** [comment]
Hi,

In our user case, we want to make authentication with Facebook optional, mainly used for synching progress data accross devices and to use (FB only) consumables.    

If the user is not logged-in to Facebook afterward, he is still able to play and we still want to track down his progress locally like if he is offline.    When he will be login back using FB, we want to merge the local progress data with the FB data.

Is there any way to emulate this behavior?

Nicolas

**Comment by albertvaka** [comment]
Yes, this flow is supported, the only implication is that after the user has logged in with FB for the first time, all the subsequent times he has to keep using FB.

What you saw before is that the user can still login as unauthenticated identity for one hour, but this is only due to the fact that the token hasn't expired yet.

Let's explain this with an example: A user downloads the game and starts playing without FB (he will get an unauthenticated identity). After some time he is super engaged with your game and wants to link it to Facebook to unlock the FB-only features and to synchronize the progress. After logging in with FB and linking the identity with it (credentials.IdentityProvider.Logins.Add and then credentials.IdentityProvider.RefreshAsync), it will become an authenticated identity. From that point on, the user has to always be authenticated with FB in order to play.

**Comment by LancelotBleu** [comment]
Thank you very much for your answer, I do appreciate it very much.

To prevent my users from having to log back using FB everytime after the first FB login, I think I can figure out a solution that is compatible with Cognito's workflow and won't break anything.

I will locally save via Unity's PlayerPrefs the values of the user after the first Cognito FB login.   Since the interface is very similar to Cognito's sync, I will simply re-use the same code to sync the values from my local PlayerPref repository to the Cognito's one when the user will finally decide to login to FB again.    It should do the trick.

Case closed.

Thanks again,

Nicolas

**Comment by albertvaka** [comment]
Note that with the Facebook SDK for Unity, if you call FB.Init and the user has already logged in with the same app before, it will give you an authentication token without asking the user to actually login again (that is: logging in all the subsequent times is completely transparent to the user!). At least this is the behaviour if the user has the Facebook app installed, I'm not sure about what happens if they use the web interface to login.

**Comment by LancelotBleu** [comment]
I think this might be the same behavior on the web version, you're right!     That's actually a very helpful information and now I can understand why once you are logged-in with FB it is ok after that.
