### ISSUE TITLE
Is there a way to get the current Date and UTC time from the cloud?

### ISSUE THREAD

**Issue by gonzaloguzzardi** [aws/aws-sdk-unity#21]
This may be a stupid question, and i apologize if it is, but I need a reliable way to know the date and time in my game, and i  thought you may already have the soulution. 
Currently i am using System.DateTime.UtcNow, but it is easily exploitable.

Sorry again, and thank you.

**Comment by weijiamao** [comment]
Hi, we don't have solution to provide accurate time over the cloud. You can get "server time" from HTTP response. For example, some AWS service response has "Date" header. But this Date header does not guarantee accurate time. 

Inaccurate time can cause "Clock Skew" issue in AWS SDK. Please check here http://mobile.awsblog.com/post/Tx2KKPVXE69XJAO/Managing-Device-Time-with-the-AWS-Mobile-SDKs. In other AWS Mobile SDK -- Android and iOS SDK -- SDK can detect and correct the skewed time for you. But in Unity SDK, we have difficulty to implement such feature because the HTTP client(WWW) has limitation that http message body cannot be accessed when receives error http status code.  We are diving deeper on the clock skew issue.
