### ISSUE TITLE
Unity AWS assemblies

### ISSUE THREAD

**Issue by hgray** [aws/aws-sdk-unity#41]
Would it be possible for future releases to provide both the source and the assemblies? We have run into some issues with large CSharp libraries generated by Unity and find that having elements in separate dlls reduces the issue.

Thanks

**Comment by weijiamao** [comment]
Thank you very much for your feedback. Your feedback will help us prioritize our work.

**Comment by karthiksaligrama** [comment]
Please take a look at https://github.com/aws/aws-sdk-net/tree/unityv3 and our blog post http://mobile.awsblog.com/post/Tx1K3R5975IFX8/AWS-SDK-for-Unity-Is-Now-Part-of-AWS-SDK-for-NET. I'm closing this issue here and issues related to AWS Assembly would now be tracked from  https://github.com/aws/aws-sdk-net/issues
