### ISSUE TITLE
DynamoDB - DynamoDBContext CreateBatchWrite - Exception: Network on game thread

### ISSUE THREAD

**Issue by andreineacsu** [aws/aws-sdk-unity#88]
Hello,

We are using DynamoDB in about Unity3D game. 
At this moment, we are getting an exception (Exception: Network on game thread) when calling DynamoDBContext's CreateBatchWrite method. Please find attached a screenshot containing all other Exceptions caused by the first one (Exception: Network on game thread). 
The exception seams to be thrown on the BatchWrite constructor method on this line of code:
"Table table = Context.GetTargetTable(StorageConfig, Config);".

We managed to avoid this exception by calling "GetTable" immediately after our game loads, long before we need to call DynamoDBContext's CreateBatchWrite. 

Thank you,
Andrei

**Comment by karthiksaligrama** [comment]
This is a known problem. We are working on it. You can also avoid it by using Threadpool thread to make dynamodb calls.

**Comment by andreineacsu** [comment]
Can you please let me know when a new version fixing this issue might be available? Thanks!

**Comment by karthiksaligrama** [comment]
at this moment i don't have a date for the fix. I'll update here as soon as i have a fix

**Comment by madangosain** [comment]
I am also seeing this error using high level object persistence model (latest AWS-unity sdk with unity 5.2 mac-os) when calling:

DynamoDBContext.QueryAsync(QueryOperationConfig) 

Alternatively if I call 
DynamoDBContext.Client.QueryAsync(QueryRequest), directly, it works okay.

Do we have any update on this issue? Otherwise can you please elaborate on recommended workaround? 

Thanks

**Comment by karthiksaligrama** [comment]
Fixed in version 3 for aws sdk for unity. If you continue to face problems please raise a new issue on our [dotnet sdk repository](https://github/aws/aws-sdk-net)
